SELECT j."NM_JURUSAN", f."NM_FAKULTAS", COUNT(mhs."NIM") AS "JML_MHS" 
FROM jurusan j
LEFT JOIN mahasiswa mhs
ON j."KD_JURUSAN" = mhs."KD_JURUSAN"
LEFT JOIN fakultas f
ON j."KD_FAKULTAS" = f."KD_FAKULTAS"
GROUP BY j."NM_JURUSAN", f."NM_FAKULTAS"
HAVING COUNT(mhs."KD_JURUSAN") = 0;